# Generated by Django 5.0.1 on 2024-01-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Categories'},
        ),
    ]
